/* Generated by           cobc 3.1-dev.0 */
/* Generated from         anothersample.cbl */
/* Generated at           May 13 2020 22:42:08 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C anothersample.cbl anothersubsample.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"anothersample.cbl"
#define  COB_PACKAGE_VERSION		"3.1-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"May 13 2020 22:42:08"
#define  COB_MODULE_DATE		20200513
#define  COB_MODULE_TIME		224208

/* Global variables */
#include "anothersample.c.h"

/* Function prototypes */

int		anothersample (void);
static int		anothersample_ (const int);
static void		anothersample_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'anothersample' */

/* ENTRY 'anothersample' */

int
anothersample ()
{
  return anothersample_ (0);
}

static int
anothersample_ (const int entry)
{
  /* Program local variables */
  #include "anothersample.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     anothersample           : anothersample.cbl */
  l_2:;

  /* Line: 8         : DISPLAY            : anothersample.cbl */
  cob_display (0, 1, 1, &c_1);

  /* Line: 9         : CALL               : anothersample.cbl */
  {
    union {
      unsigned char data[2];
      cob_s64_t     datall;
      cob_u64_t     dataull;
      int           dataint;
    } content_1;
    cob_field      content_f_1;
    cob_field_attr content_a_1;

    cob_field_constant (&f_8, &content_f_1 , &content_a_1 , &content_1);
    cob_procedure_params[0] = &content_f_1;
    cob_glob_ptr->cob_call_params = 1;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_anothersubsample.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
    {
      call_anothersubsample.funcvoid = cob_resolve_cobol ("anothersubsample", 0, 1);
    }
    b_2 = ((int (*)(void *))call_anothersubsample.funcint) (content_1.data);
  }

  /* Line: 11        : CALL               : anothersample.cbl */
  {
    union {
      unsigned char data[10];
      cob_s64_t     datall;
      cob_u64_t     dataull;
      int           dataint;
    } content_1;
    cob_field      content_f_1;
    cob_field_attr content_a_1;

    cob_field_constant (&f_9, &content_f_1 , &content_a_1 , &content_1);
    cob_procedure_params[0] = &content_f_1;
    cob_glob_ptr->cob_call_params = 1;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely((cob_glob_ptr->cob_exception_code & 0x0b00) == 0x0b00)) cob_glob_ptr->cob_exception_code = 0;
        if (unlikely(call_anothersubsample.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel))
    {
      call_anothersubsample.funcvoid = cob_resolve_cobol ("anothersubsample", 0, 1);
    }
    b_2 = ((int (*)(void *))call_anothersubsample.funcint) (content_1.data);
  }

  /* Line: 13        : DISPLAY            : anothersample.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 14        : STOP RUN           : anothersample.cbl */
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  anothersample_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memcpy (b_8, "01", 2);
  memcpy (b_9, "0123456789", 10);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  call_anothersubsample.funcvoid = NULL;
  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'anothersample' */

/* Initialize module structure for anothersample */
static void anothersample_module_init (cob_module *module)
{
  module->module_name = "anothersample";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())anothersample;
  module->module_cancel.funcptr = (void *(*)())anothersample_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

