/* Generated by           cobc 3.1-dev.0 */
/* Generated from         anothersubsample.cbl */
/* Generated at           May 13 2020 22:42:08 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C anothersample.cbl anothersubsample.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};

