/* Generated by           cobc 3.1-dev.0 */
/* Generated from         anothersample.cbl */
/* Generated at           May 13 2020 22:42:08 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C anothersample.cbl anothersubsample.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {5, (cob_u8_ptr)"Hello", &a_1};
static const cob_field c_2	= {5, (cob_u8_ptr)"World", &a_1};

