/* Generated by           cobc 3.1-dev.0 */
/* Generated from         anothersample.cbl */
/* Generated at           May 13 2020 22:42:08 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C anothersample.cbl anothersubsample.cbl */

/* Program local variables for 'anothersample' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_anothersubsample;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[2] __attribute__((aligned));	/* WS-SMALL */
static cob_u8_t	b_9[10] __attribute__((aligned));	/* WS-BIG */

/* End of local data storage */


/* Fields */
static cob_field f_8	= {2, b_8, &a_2};	/* WS-SMALL */
static cob_field f_9	= {10, b_9, &a_2};	/* WS-BIG */

/* End of fields */

