/* Generated by           cobc 3.1-dev.0 */
/* Generated from         /home/casa/dev/git/cobol-hello-world/datatypes.cob */
/* Generated at           May 20 2020 21:12:33 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/casa/dev/git/cobol-hello-world/datatypes.cob */

/* Program local variables for 'datatypes' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[93] __attribute__((aligned));	/* numeric-data */
static cob_u8_t	b_34[12] __attribute__((aligned));	/* floating-data */
static cob_u8_t	b_37[25] __attribute__((aligned));	/* special-data */
static cob_u8_t	b_43[101] __attribute__((aligned));	/* alphanumeric-data */
static cob_u8_t	b_50[116] __attribute__((aligned));	/* national-data */

/* End of local data storage */


/* Fields */
static cob_field f_8	= {93, b_8, &a_36};	/* numeric-data */
static cob_field f_9	= {5, b_8, &a_7};	/* disp */
static cob_field f_10	= {5, b_8 + 5, &a_8};	/* disp-u */
static cob_field f_11	= {4, b_8 + 10, &a_9};	/* dispp */
static cob_field f_12	= {4, b_8 + 14, &a_10};	/* dispp-u */
static cob_field f_13	= {4, b_8 + 18, &a_11};	/* disppp */
static cob_field f_14	= {4, b_8 + 22, &a_12};	/* disppp-u */
static cob_field f_15	= {4, b_8 + 26, &a_13};	/* bin */
static cob_field f_16	= {4, b_8 + 30, &a_14};	/* bin-u */
static cob_field f_17	= {3, b_8 + 34, &a_15};	/* cmp3 */
static cob_field f_18	= {3, b_8 + 37, &a_16};	/* cmp3-u */
static cob_field f_19	= {4, b_8 + 40, &a_2};	/* cmp5 */
static cob_field f_20	= {4, b_8 + 44, &a_17};	/* cmp5-u */
static cob_field f_21	= {3, b_8 + 48, &a_18};	/* cmp6 */
static cob_field f_22	= {3, b_8 + 51, &a_19};	/* cmpx */
static cob_field f_23	= {3, b_8 + 54, &a_20};	/* cmpx-u */
static cob_field f_24	= {3, b_8 + 57, &a_19};	/* cmpn */
static cob_field f_25	= {3, b_8 + 60, &a_20};	/* cmpn-u */
static cob_field f_26	= {1, b_8 + 63, &a_21};	/* chr */
static cob_field f_27	= {1, b_8 + 64, &a_22};	/* chr-u */
static cob_field f_28	= {2, b_8 + 65, &a_23};	/* shrt */
static cob_field f_29	= {2, b_8 + 67, &a_24};	/* shrt-u */
static cob_field f_30	= {4, b_8 + 69, &a_25};	/* long */
static cob_field f_31	= {4, b_8 + 73, &a_26};	/* long-u */
static cob_field f_32	= {8, b_8 + 77, &a_27};	/* dble */
static cob_field f_33	= {8, b_8 + 85, &a_28};	/* dble-u */
static cob_field f_34	= {12, b_34, &a_36};	/* floating-data */
static cob_field f_35	= {8, b_34, &a_29};	/* dbl */
static cob_field f_36	= {4, b_34 + 8, &a_30};	/* flt */
static cob_field f_37	= {25, b_37, &a_36};	/* special-data */
static cob_field f_38	= {1, b_37, &a_31};	/* r2d2 */
static cob_field f_39	= {8, b_37 + 1, &a_32};	/* point */
static cob_field f_40	= {8, b_37 + 9, &a_32};	/* ppoint */
static cob_field f_41	= {4, b_37 + 17, &a_33};	/* idx */
static cob_field f_42	= {4, b_37 + 21, &a_33};	/* hnd */
static cob_field f_43	= {101, b_43, &a_36};	/* alphanumeric-data */
static cob_field f_44	= {36, b_43, &a_34};	/* alpnum */
static cob_field f_45	= {36, b_43 + 36, &a_34};	/* alpha */
static cob_field f_46	= {7, b_43 + 72, &a_3};	/* edit-num1 */
static cob_field f_47	= {7, b_43 + 79, &a_4};	/* edit-num2 */
static cob_field f_48	= {7, b_43 + 86, &a_5};	/* edit-num3 */
static cob_field f_49	= {8, b_43 + 93, &a_6};	/* edit-num4 */
static cob_field f_50	= {116, b_50, &a_36};	/* national-data */
static cob_field f_51	= {72, b_50, &a_35};	/* nat */
static cob_field f_53	= {7, b_50 + 87, &a_3};	/* net-num1 */
static cob_field f_54	= {7, b_50 + 94, &a_4};	/* net-num2 */
static cob_field f_55	= {7, b_50 + 101, &a_5};	/* net-num3 */
static cob_field f_56	= {8, b_50 + 108, &a_6};	/* net-num4 */

/* End of fields */

