/* Generated by           cobc 3.1-dev.0 */
/* Generated from         /home/casa/dev/git/cobol-hello-world/datatypes.cob */
/* Generated at           May 20 2020 21:12:33 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/casa/dev/git/cobol-hello-world/datatypes.cob */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'-', 2},
	{'9', 1},
	{'.', 1},
	{'9', 3},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'+', 2},
	{'9', 1},
	{'.', 1},
	{'9', 3},
	{'\0', 1}
};
static const cob_pic_symbol p_3[] = {
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 3},
	{'\0', 1}
};
static const cob_pic_symbol p_4[] = {
	{'-', 1},
	{'Z', 2},
	{'9', 1},
	{'.', 1},
	{'9', 3},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x11,   5,   3, 0x0041, NULL};
static const cob_field_attr a_3 =	{0x24,   5,   3, 0x0001, p_1};
static const cob_field_attr a_4 =	{0x24,   5,   3, 0x0001, p_2};
static const cob_field_attr a_5 =	{0x24,   6,   3, 0x0000, p_3};
static const cob_field_attr a_6 =	{0x24,   6,   3, 0x0009, p_4};
static const cob_field_attr a_7 =	{0x10,   5,   3, 0x0001, NULL};
static const cob_field_attr a_8 =	{0x10,   5,   3, 0x0000, NULL};
static const cob_field_attr a_9 =	{0x10,   8,   8, 0x0001, NULL};
static const cob_field_attr a_10 =	{0x10,   8,   8, 0x0000, NULL};
static const cob_field_attr a_11 =	{0x10,   8,  -4, 0x0001, NULL};
static const cob_field_attr a_12 =	{0x10,   8,  -4, 0x0000, NULL};
static const cob_field_attr a_13 =	{0x11,   5,   3, 0x0821, NULL};
static const cob_field_attr a_14 =	{0x11,   5,   3, 0x0820, NULL};
static const cob_field_attr a_15 =	{0x12,   5,   3, 0x0001, NULL};
static const cob_field_attr a_16 =	{0x12,   5,   3, 0x0000, NULL};
static const cob_field_attr a_17 =	{0x11,   5,   3, 0x0040, NULL};
static const cob_field_attr a_18 =	{0x12,   5,   3, 0x0100, NULL};
static const cob_field_attr a_19 =	{0x11,   5,   3, 0x0021, NULL};
static const cob_field_attr a_20 =	{0x11,   5,   3, 0x0020, NULL};
static const cob_field_attr a_21 =	{0x11,   2,   0, 0x0041, NULL};
static const cob_field_attr a_22 =	{0x11,   2,   0, 0x0040, NULL};
static const cob_field_attr a_23 =	{0x11,   4,   0, 0x0041, NULL};
static const cob_field_attr a_24 =	{0x11,   4,   0, 0x0040, NULL};
static const cob_field_attr a_25 =	{0x11,   9,   0, 0x0041, NULL};
static const cob_field_attr a_26 =	{0x11,   9,   0, 0x0040, NULL};
static const cob_field_attr a_27 =	{0x11,  18,   0, 0x0041, NULL};
static const cob_field_attr a_28 =	{0x11,  18,   0, 0x0040, NULL};
static const cob_field_attr a_29 =	{0x14,  34,  17, 0x0201, NULL};
static const cob_field_attr a_30 =	{0x13,  15,   8, 0x0201, NULL};
static const cob_field_attr a_31 =	{0x02,   3,   0, 0x0000, NULL};
static const cob_field_attr a_32 =	{0x11,  17,   0, 0x0080, NULL};
static const cob_field_attr a_33 =	{0x11,   9,   0, 0x0001, NULL};
static const cob_field_attr a_34 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_35 =	{0x40,   0,   0, 0x0000, NULL};
static const cob_field_attr a_36 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_37 =	{0x10,   4,   2, 0x0007, NULL};
static const cob_field_attr a_38 =	{0x10,   4,   2, 0x1000, NULL};
static const cob_field_attr a_39 =	{0x10,   7,   7, 0x0007, NULL};
static const cob_field_attr a_40 =	{0x10,   7,   7, 0x1000, NULL};
static const cob_field_attr a_41 =	{0x10,   8,   0, 0x0007, NULL};
static const cob_field_attr a_42 =	{0x10,   8,   0, 0x1000, NULL};
static const cob_field_attr a_43 =	{0x10,   3,   0, 0x0007, NULL};
static const cob_field_attr a_44 =	{0x10,   3,   0, 0x1000, NULL};
static const cob_field_attr a_45 =	{0x10,   5,   0, 0x0007, NULL};
static const cob_field_attr a_46 =	{0x10,   5,   0, 0x1000, NULL};
static const cob_field_attr a_47 =	{0x10,  10,   0, 0x0007, NULL};
static const cob_field_attr a_48 =	{0x10,  10,   0, 0x1000, NULL};
static const cob_field_attr a_49 =	{0x10,   6, -33, 0x0007, NULL};
static const cob_field_attr a_50 =	{0x10,   6, -33, 0x1000, NULL};
static const cob_field_attr a_51 =	{0x10,   1,   0, 0x1000, NULL};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {5, (cob_u8_ptr)"types", &a_1};
static const cob_field c_2	= {5, (cob_u8_ptr)"-1234", &a_37};
static const cob_field c_3	= {4, (cob_u8_ptr)"1234", &a_38};
static const cob_field c_4	= {8, (cob_u8_ptr)"-0000123", &a_39};
static const cob_field c_5	= {7, (cob_u8_ptr)"0000123", &a_40};
static const cob_field c_6	= {9, (cob_u8_ptr)"-12340000", &a_41};
static const cob_field c_7	= {8, (cob_u8_ptr)"12340000", &a_42};
static const cob_field c_8	= {4, (cob_u8_ptr)"-128", &a_43};
static const cob_field c_9	= {3, (cob_u8_ptr)"254", &a_44};
static const cob_field c_10	= {6, (cob_u8_ptr)"-32768", &a_45};
static const cob_field c_11	= {5, (cob_u8_ptr)"65535", &a_46};
static const cob_field c_12	= {11, (cob_u8_ptr)"-2147483648", &a_47};
static const cob_field c_13	= {10, (cob_u8_ptr)"4294967295", &a_48};
static const cob_field c_14	= {11, (cob_u8_ptr)"-4294967295", &a_47};
static const cob_field c_15	= {10, (cob_u8_ptr)"8294967295", &a_48};
static const cob_field c_16	= {7, (cob_u8_ptr)"-340282", &a_49};
static const cob_field c_17	= {6, (cob_u8_ptr)"340282", &a_50};
static const cob_field c_18	= {1, (cob_u8_ptr)"6", &a_51};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


/* Strings */
static const char st_1[]	= "datatypes";
static const char st_2[]	= "SET";
static const char st_3[]	= "MOVE";
static const char st_4[]	= "DISPLAY";
static const char st_5[]	= "GOBACK";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/home/casa/dev/git/cobol-hello-world/datatypes.cob"};
