/* Generated by           cobc 3.1-dev.0 */
/* Generated from         /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
/* Generated at           May 19 2020 12:22:46 */
/* GnuCOBOL build date    May 16 2020 05:32:07 */
/* GnuCOBOL package date  May 11 2020 23:42:04 UTC */
/* Compile command        cobc -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */

/* Program local variables for 'DATATYPES' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[103] __attribute__((aligned));	/* WS-GROUP */

/* End of local data storage */


/* Fields */
static cob_field f_8	= {103, b_8, &a_1};	/* WS-GROUP */
static cob_field f_9	= {2, b_8, &a_2};	/* WS-INTEGER */
static cob_field f_10	= {5, b_8 + 2, &a_3};	/* WS-DECIMAL */
static cob_field f_11	= {5, b_8 + 7, &a_4};	/* WS-UNSIGNED-DECIMAL */
static cob_field f_12	= {6, b_8 + 12, &a_5};	/* WS-ALPHABETIC */
static cob_field f_13	= {5, b_8 + 18, &a_5};	/* WS-ALPHANUMERIC */
static cob_field f_14	= {10, b_8 + 23, &a_6};	/* WS-FORMATED-DECIMAL */
static cob_field f_15	= {10, b_8 + 33, &a_7};	/* WS-FORMATED-INTEGER */
static cob_field f_16	= {60, b_8 + 43, &a_1};	/* WS-SUBGROUP */
static cob_field f_17	= {20, b_8 + 43, &a_5};	/* WS-SUBGROUP-F */
static cob_field f_18	= {20, b_8 + 63, &a_5};	/* WS-SUBGROUP-L */
static cob_field f_19	= {20, b_8 + 83, &a_5};	/* WS-SUBGROUP-B */

/* End of fields */

