/* Generated by           cobc 3.1-dev.0 */
/* Generated from         /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
/* Generated at           May 19 2020 12:22:46 */
/* GnuCOBOL build date    May 16 2020 05:32:07 */
/* GnuCOBOL package date  May 11 2020 23:42:04 UTC */
/* Compile command        cobc -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl"
#define  COB_PACKAGE_VERSION		"3.1-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"May 19 2020 12:22:46"
#define  COB_MODULE_DATE		20200519
#define  COB_MODULE_TIME		122246

/* Global variables */
#include "datatypes.c.h"

/* Function prototypes */

static int		DATATYPES ();
static int		DATATYPES_ (const int);
static void		DATATYPES_module_init (cob_module *module);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (DATATYPES ());
}

/* Functions */

/* PROGRAM-ID 'DATATYPES' */

/* ENTRY 'DATATYPES' */

static int
DATATYPES ()
{
  return DATATYPES_ (0);
}

static int
DATATYPES_ (const int entry)
{
  /* Program local variables */
  #include "datatypes.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 23        : Entry     DATATYPES               : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  l_2:;
  module->module_stmt = 0x00100017;
  cob_trace_entry (st_1);
  module->module_stmt = 0x00100019;
  cob_trace_sect (NULL);

  /* Line: 25        : Paragraph 0001-START              : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  cob_trace_para (st_2);

  /* Line: 26        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001A;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_8);

  /* Line: 27        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001B;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_9);

  /* Line: 28        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001C;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_10);

  /* Line: 29        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001D;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_11);

  /* Line: 30        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001E;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_12);

  /* Line: 31        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x0010001F;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_13);

  /* Line: 32        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100020;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_14);

  /* Line: 33        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100021;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_15);

  /* Line: 34        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100022;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_16);

  /* Line: 35        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100023;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_17);

  /* Line: 36        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100024;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_18);

  /* Line: 37        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100025;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &f_19);

  /* Line: 38        : DISPLAY            : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100026;
  cob_trace_stmt (st_3);
  cob_display (0, 1, 1, &c_1);

  /* Line: 39        : STOP RUN           : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100027;
  cob_trace_stmt (st_4);
  cob_stop_run (b_2);

  /* Line: 40        : Paragraph 0001-END                : /Users/bpacheco/dev/personal_git/cobol-hello-world/datatypes.cbl */
  module->module_stmt = 0x00100028;
  cob_trace_para (st_5);

  module->module_stmt = 0x0010002A;

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_exit (st_1);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  DATATYPES_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memcpy (b_8, "45", 2);
  memcpy (b_8 + 2, "1234u", 5);
  memcpy (b_8 + 7, "12345", 5);
  memcpy (b_8 + 12, "ABCDEF", 6);
  memcpy (b_8 + 18, "A121$", 5);
  cob_move ((cob_field *)&c_2, &f_14);
  cob_move ((cob_field *)&c_3, &f_15);
  memset (b_8 + 43, 102, 20);
  memset (b_8 + 63, 108, 20);
  memset (b_8 + 83, 98, 20);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'DATATYPES' */

/* Initialize module structure for DATATYPES */
static void DATATYPES_module_init (cob_module *module)
{
  module->module_name = "DATATYPES";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())DATATYPES;
  module->module_cancel.funcptr = (void *(*)())DATATYPES_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 6;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = st_source_files;
}

/* End functions */

