/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
/* Generated at           Mai 23 2020 10:02:19 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */

/* Program local variables for 'func' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	func_DVD;
static cob_call_union	func_MLP;

/* Call parameters */
cob_field		*cob_procedure_params[2];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Dynamic field FUNCTION-ID pointers */
cob_field	*cob_dyn_0 = NULL;
cob_field	*cob_dyn_1 = NULL;

/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[4] __attribute__((aligned));	/* argA */
static cob_u8_t	b_7[4] __attribute__((aligned));	/* argB */

/* End of data storage */


/* Fields */
static cob_field f_6	= {4, b_6, &a_2};	/* argA */
static cob_field f_7	= {4, b_7, &a_2};	/* argB */

/* End of fields */

