/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
/* Generated at           Mai 23 2020 10:02:19 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/olegs/projects/gnucobol-debug/test/resources/func.cbl"
#define  COB_PACKAGE_VERSION		"2.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Mai 23 2020 10:02:19"
#define  COB_MODULE_DATE		20200523
#define  COB_MODULE_TIME		100219

/* Global variables */
#include "func.c.h"

/* Function prototypes */

static int		func ();
static int		func_ (const int);
cob_field		*DVD (cob_field **, const int, cob_field *, cob_field *);
static cob_field	*DVD_ (const int, cob_u8_t *, cob_u8_t *);
cob_field		*MLP (cob_field **, const int, cob_field *, cob_field *);
static cob_field	*MLP_ (const int, cob_u8_t *, cob_u8_t *);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (func ());
}

/* Functions */

/* PROGRAM-ID 'func' */

/* ENTRY 'func' */

static int
func ()
{
  return func_ (0);
}

static int
func_ (const int entry)
{
  /* Program local variables */
  #include "func.c.l1.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 13        : Entry     func                    : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 13);
  cob_trace_section (st_3, st_1, 13);
  cob_trace_section (st_4, st_1, 13);

  /* Line: 13        : DISPLAY            : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  cob_set_location (st_1, 13, NULL, NULL, st_5);
  cob_display (0, 1, 2, &c_1, func_DVD.funcfld (&cob_dyn_0, 2, &f_6, &f_7));

  /* Line: 14        : DISPLAY            : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  cob_set_location (st_1, 14, NULL, NULL, st_5);
  cob_display (0, 1, 2, &c_2, func_MLP.funcfld (&cob_dyn_1, 2, &f_6, &f_7));

  /* Line: 15        : STOP RUN           : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  cob_set_location (st_1, 15, NULL, NULL, st_6);
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Deallocate dynamic FUNCTION-ID fields */
  if (cob_dyn_0) {
    if (cob_dyn_0->data) {
      cob_free (cob_dyn_0->data);
    }
    cob_free (cob_dyn_0);
    cob_dyn_0 = NULL;
  }
  if (cob_dyn_1) {
    if (cob_dyn_1->data) {
      cob_free (cob_dyn_1->data);
    }
    cob_free (cob_dyn_1);
    cob_dyn_1 = NULL;
  }

  /* Trace program exit */
  cob_trace_section (st_7, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  func_MLP.funcvoid = cob_resolve_func ("MLP");
  func_DVD.funcvoid = cob_resolve_func ("DVD");
  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "func";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())func;
  module->module_cancel.funcptr = (void *(*)())func_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  cob_move ((cob_field *)&c_3, &f_6);
  cob_move ((cob_field *)&c_4, &f_7);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'func' */

/* FUNCTION-ID 'dvd' */

/* ENTRY 'DVD' */

cob_field *
DVD (cob_field **cob_fret, const int cob_pam, cob_field *f0, cob_field *f1)
{
  struct cob_func_loc	*floc;

  /* Save environment */
  floc = cob_save_func (cob_fret, cob_pam, 2, f0, f1);
  cob_call_params = cob_get_global_ptr ()->cob_call_params;
  floc->ret_fld = DVD_ (0, floc->data[0], floc->data[1]);
  **cob_fret = *floc->ret_fld;
  /* Restore environment */
  cob_restore_func (floc);
  return *cob_fret;
}

static cob_field *
DVD_ (const int entry, cob_u8_t *b_14, cob_u8_t *b_15)
{
  /* Program local variables */
  #include "func.c.l2.h"

  /* Start of function code */

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return NULL;

  /* Initialize module structure */
  module->module_name = "dvd";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())DVD;
  module->module_cancel.funcptr = NULL;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 1;
  module->module_param_cnt = 2;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (1U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;
  frame_overflow = frame_ptr + 63 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_push (2, &d0, &d1);

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_14 = NULL;
  case 1:
  	b_15 = NULL;
  default:
	break;
  }

  /* Storage for returning item */
  b_16 = cob_malloc (4U);

  /* Entry dispatch */
  goto l_5;

  /* PROCEDURE DIVISION */

  /* Line: 27        : Entry     dvd                     : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  l_5:;
  cob_trace_section (st_8, st_1, 27);
  cob_trace_section (st_3, st_1, 27);
  cob_trace_section (st_4, st_1, 27);

  /* Line: 27        : COMPUTE            : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  cob_set_location (st_1, 27, NULL, NULL, st_9);
  cob_decimal_set_field (d0, COB_SET_DATA (f_14, b_14));
  cob_decimal_set_field (d1, COB_SET_DATA (f_15, b_15));
  cob_decimal_div (d0, d1);
  cob_decimal_get_field (d0, COB_SET_DATA (f_16, b_16), 0);

  /* Program exit */

  /* Free decimal structures */
  cob_decimal_pop (2, d0, d1);

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Trace program exit */
  cob_trace_section (st_10, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);

  /* Program return */
  b_10 = cob_get_int (COB_SET_DATA (f_16, b_16));
  return COB_SET_DATA (f_16, b_16);

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize WORKING-STORAGE */
  b_10 = 0;

  initialized = 1;
  goto P_ret_initialize;
}

/* End FUNCTION-ID 'dvd' */

/* FUNCTION-ID 'mlp' */

/* ENTRY 'MLP' */

cob_field *
MLP (cob_field **cob_fret, const int cob_pam, cob_field *f0, cob_field *f1)
{
  struct cob_func_loc	*floc;

  /* Save environment */
  floc = cob_save_func (cob_fret, cob_pam, 2, f0, f1);
  cob_call_params = cob_get_global_ptr ()->cob_call_params;
  floc->ret_fld = MLP_ (0, floc->data[0], floc->data[1]);
  **cob_fret = *floc->ret_fld;
  /* Restore environment */
  cob_restore_func (floc);
  return *cob_fret;
}

static cob_field *
MLP_ (const int entry, cob_u8_t *b_23, cob_u8_t *b_24)
{
  /* Program local variables */
  #include "func.c.l3.h"

  /* Start of function code */

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return NULL;

  /* Initialize module structure */
  module->module_name = "mlp";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())MLP;
  module->module_cancel.funcptr = NULL;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 1;
  module->module_param_cnt = 2;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Set address of module parameter list */
  cob_procedure_params = cob_malloc (1U * sizeof(void *));
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_stack = cob_malloc (63U * sizeof(struct cob_frame));
  frame_ptr = frame_stack;
  frame_overflow = frame_ptr + 63 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_push (2, &d0, &d1);

  /* Set not passed parameter pointers to NULL */
  switch (cob_call_params) {
  case 0:
  	b_23 = NULL;
  case 1:
  	b_24 = NULL;
  default:
	break;
  }

  /* Storage for returning item */
  b_25 = cob_malloc (4U);

  /* Entry dispatch */
  goto l_8;

  /* PROCEDURE DIVISION */

  /* Line: 39        : Entry     mlp                     : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  l_8:;
  cob_trace_section (st_11, st_1, 39);
  cob_trace_section (st_3, st_1, 39);
  cob_trace_section (st_4, st_1, 39);

  /* Line: 39        : COMPUTE            : /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
  cob_set_location (st_1, 39, NULL, NULL, st_9);
  cob_decimal_set_field (d0, COB_SET_DATA (f_23, b_23));
  cob_decimal_set_field (d1, COB_SET_DATA (f_24, b_24));
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, COB_SET_DATA (f_25, b_25), 0);

  /* Program exit */

  /* Free decimal structures */
  cob_decimal_pop (2, d0, d1);

  /* Free frame stack / call parameters */
  cob_free (frame_stack);
  cob_free (cob_procedure_params);

  /* Trace program exit */
  cob_trace_section (st_12, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Free for recursive module */
  cob_module_free (&module);

  /* Program return */
  b_19 = cob_get_int (COB_SET_DATA (f_25, b_25));
  return COB_SET_DATA (f_25, b_25);

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize WORKING-STORAGE */
  b_19 = 0;

  initialized = 1;
  goto P_ret_initialize;
}

/* End FUNCTION-ID 'mlp' */

/* End functions */

