/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
/* Generated at           Mai 23 2020 10:02:19 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */

/* Program local variables for 'mlp' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer for recursive */
cob_module		*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
	cob_decimal	*d0 = NULL;
	cob_decimal	*d1 = NULL;


/* LINKAGE SECTION (Items not referenced by USING clause) */
unsigned char	*b_25 = NULL;  /* result */


/* Call parameters */
cob_field		**cob_procedure_params;

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	*frame_stack;


/* Data storage */
static int	b_19;	/* RETURN-CODE */

/* End of data storage */


/* Fields */
static cob_field f_23	= {4, NULL, &a_2};	/* argA */
static cob_field f_24	= {4, NULL, &a_2};	/* argB */
static cob_field f_25	= {4, NULL, &a_2};	/* result */

/* End of fields */

