/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */
/* Generated at           Mai 23 2020 10:02:19 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/olegs/projects/gnucobol-debug/test/resources/func.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   4,   2, 0x0001, NULL};
static const cob_field_attr a_3 =	{0x10,   2,   0, 0x1000, NULL};
static const cob_field_attr a_4 =	{0x10,   1,   0, 0x1000, NULL};


/* Constants */
static const cob_field c_1	= {10, (cob_u8_ptr)"Division: ", &a_1};
static const cob_field c_2	= {16, (cob_u8_ptr)"Multiplication: ", &a_1};
static const cob_field c_3	= {2, (cob_u8_ptr)"10", &a_3};
static const cob_field c_4	= {1, (cob_u8_ptr)"3", &a_4};


/* Strings */
static const char st_1[]	= "/home/olegs/projects/gnucobol-debug/test/resources/func.cbl";
static const char st_2[]	= "Entry:     func";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: (None)";
static const char st_5[]	= "DISPLAY";
static const char st_6[]	= "STOP RUN";
static const char st_7[]	= "Exit:      func";
static const char st_8[]	= "Entry:     dvd";
static const char st_9[]	= "COMPUTE";
static const char st_10[]	= "Exit:      dvd";
static const char st_11[]	= "Entry:     mlp";
static const char st_12[]	= "Exit:      mlp";

	/* Decimal constants */
