/* Generated by           cobc 3.1.1.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/hello3.cbl */
/* Generated at           Dec 16 2020 11:04:17 */
/* GnuCOBOL build date    Dec 12 2020 10:39:10 */
/* GnuCOBOL package date  Dec 08 2020 22:56:13 UTC */
/* Compile command        cobc -free -x -g -fsource-location -ftraceall -Q --coverage -A --coverage -v /home/olegs/projects/gnucobol-debug/test/resources/hello3.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x21,   0,   0, 0x0000, NULL};


/* Constants */
static const cob_field c_1	= {6, (cob_u8_ptr)"Hello ", &a_1};


/* Strings */
static const char st_1[]	= "hello3";
static const char st_2[]	= "MOVE";
static const char st_3[]	= "DISPLAY";
static const char st_4[]	= "STOP RUN";


/* Source file names */
static const char *st_source_files[]	= { "" 
		,"/home/olegs/projects/gnucobol-debug/test/resources/hello3.cbl"};
