/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl */
/* Generated at           Apr 23 2020 17:55:55 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -d -fdebugging-line -fsource-location -ftraceall /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl subsample.cbl subsubsample.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/olegs/projects/gnucobol-debug/test/resources/hello.cbl"
#define  COB_PACKAGE_VERSION		"2.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 23 2020 17:55:55"
#define  COB_MODULE_DATE		20200423
#define  COB_MODULE_TIME		175555

/* Global variables */
#include "hello.c.h"

/* Function prototypes */

static int		hello ();
static int		hello_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (hello ());
}

/* Functions */

/* PROGRAM-ID 'hello' */

/* ENTRY 'hello' */

static int
hello ()
{
  return hello_ (0);
}

static int
hello_ (const int entry)
{
  /* Program local variables */
  #include "hello.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 7         : Entry     hello                   : /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 7);
  cob_trace_section (st_3, st_1, 7);
  cob_trace_section (st_4, st_1, 7);

  /* Line: 7         : MOVE               : /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl */
  cob_set_location (st_1, 7, NULL, NULL, st_5);
  memcpy (b_6, "World", 5);

  /* Line: 8         : DISPLAY            : /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl */
  cob_set_location (st_1, 8, NULL, NULL, st_6);
  cob_display (0, 1, 2, &c_1, &f_6);

  /* Line: 9         : STOP RUN           : /home/olegs/projects/gnucobol-debug/test/resources/hello.cbl */
  cob_set_location (st_1, 9, NULL, NULL, st_7);
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_8, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "hello";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())hello;
  module->module_cancel.funcptr = (void *(*)())hello_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memset (b_6, 32, 5);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'hello' */

/* End functions */

