/* Generated by           cobc 3.1-dev.0 */
/* Generated from         petstore.cbl */
/* Generated at           May 13 2020 22:44:45 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C petstore.cbl */

/* Program local variables for 'PETSTORE' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;

/* Decimal structures */
cob_decimal	*d0 = NULL;
cob_decimal	*d1 = NULL;


/* Subscripts */
int		i0;

/* Local cob_field items */
cob_field		f0;


/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_8[2900] __attribute__((aligned));	/* WS-ITEM */
static int	b_9;	/* I */
static cob_u8_t	b_14[17] __attribute__((aligned));	/* WS-BILL */
static cob_u8_t	b_18[8] __attribute__((aligned));	/* WS-CONTROL */
static cob_u8_t	b_24[50] __attribute__((aligned));	/* HEADING-LINE1 */
static cob_u8_t	b_32[50] __attribute__((aligned));	/* HEADING-LINE2 */
static cob_u8_t	b_40[50] __attribute__((aligned));	/* ITEM-LINE */
static cob_u8_t	b_48[50] __attribute__((aligned));	/* TOTAL-LINE1 */
static cob_u8_t	b_51[50] __attribute__((aligned));	/* TOTAL-LINE2 */
static cob_u8_t	b_56[50] __attribute__((aligned));	/* TOTAL-LINE3 */
static cob_u8_t	b_61[50] __attribute__((aligned));	/* TOTAL-LINE4 */

/* End of local data storage */


/* Fields */
static cob_field f_15	= {3, b_14, &a_2};	/* TOTAL-QUANTITY */
static cob_field f_16	= {7, b_14 + 3, &a_4};	/* TOTAL-COST */
static cob_field f_17	= {7, b_14 + 10, &a_4};	/* TOTAL-COST-DISCOUNTED */
static cob_field f_19	= {3, b_18, &a_2};	/* J */
static cob_field f_20	= {1, b_18 + 3, &a_5};	/* DISCOUNT */
static cob_field f_21	= {3, b_18 + 4, &a_2};	/* MINIMUM-FOR-DISCOUNT */
static cob_field f_24	= {50, b_24, &a_6};	/* HEADING-LINE1 */
static cob_field f_32	= {50, b_32, &a_6};	/* HEADING-LINE2 */
static cob_field f_40	= {50, b_40, &a_6};	/* ITEM-LINE */
static cob_field f_43	= {10, b_40 + 18, &a_8};	/* DETAIL-PRICE */
static cob_field f_45	= {8, b_40 + 30, &a_9};	/* DETAIL-QUANTITY */
static cob_field f_47	= {10, b_40 + 40, &a_8};	/* DETAIL-COST */
static cob_field f_48	= {50, b_48, &a_6};	/* TOTAL-LINE1 */
static cob_field f_51	= {50, b_51, &a_6};	/* TOTAL-LINE2 */
static cob_field f_55	= {10, b_51 + 40, &a_10};	/* DET-TOTAL-QUANTITY */
static cob_field f_56	= {50, b_56, &a_6};	/* TOTAL-LINE3 */
static cob_field f_60	= {10, b_56 + 40, &a_8};	/* DET-TOTAL-COST */
static cob_field f_61	= {50, b_61, &a_6};	/* TOTAL-LINE4 */
static cob_field f_65	= {10, b_61 + 40, &a_8};	/* DET-TOTAL-DISCOUNTED */

/* End of fields */

