/* Generated by           cobc 3.1-dev.0 */
/* Generated from         petstore.cbl */
/* Generated at           May 13 2020 22:44:45 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C petstore.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Picture strings */

static const cob_pic_symbol p_1[] = {
	{'$', 3},
	{',', 1},
	{'$', 2},
	{'9', 1},
	{'.', 1},
	{'9', 2},
	{'\0', 1}
};
static const cob_pic_symbol p_2[] = {
	{'Z', 7},
	{'9', 1},
	{'\0', 1}
};
static const cob_pic_symbol p_3[] = {
	{'Z', 9},
	{'9', 1},
	{'\0', 1}
};


/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x1000, NULL};
static const cob_field_attr a_2 =	{0x10,   3,   0, 0x0000, NULL};
static const cob_field_attr a_3 =	{0x10,   5,   2, 0x0000, NULL};
static const cob_field_attr a_4 =	{0x10,   7,   2, 0x0000, NULL};
static const cob_field_attr a_5 =	{0x10,   1,   1, 0x0000, NULL};
static const cob_field_attr a_6 =	{0x01,   0,   0, 0x0000, NULL};
static const cob_field_attr a_7 =	{0x10,   3,   0, 0x0001, NULL};
static const cob_field_attr a_8 =	{0x24,   7,   2, 0x0000, p_1};
static const cob_field_attr a_9 =	{0x24,   8,   0, 0x0000, p_2};
static const cob_field_attr a_10 =	{0x24,  10,   0, 0x0000, p_3};

static const cob_field_attr cob_all_attr = {0x22, 0, 0, 0, NULL};


/* Constants */
static const cob_field c_1	= {49, (cob_u8_ptr)"Hi, welcome to the petstore cash register system!", &a_1};
static const cob_field c_2	= {1, (cob_u8_ptr)" ", &a_1};

static cob_field cob_all_zero	= {1, (cob_u8_ptr)"0", &cob_all_attr};


static int COB_NOINLINE
cob_get_numdisp (const void *data, const int size)
{
	const unsigned char	*p;
	int			n;
	int 			retval;
	p = (const unsigned char *)data;
	retval = 0;
	for (n = 0; n < size; ++n, ++p) {
		retval *= 10;
		if (*p > '0' && *p <= '9')
		    retval += (*p - '0');
	}
	return retval;
}

