/* Generated by           cobc 3.1-dev.0 */
/* Generated from         petstore.cbl */
/* Generated at           May 13 2020 22:44:45 */
/* GnuCOBOL build date    Apr 28 2020 22:46:23 */
/* GnuCOBOL package date  Apr 28 2020 12:55:27 UTC */
/* Compile command        cobc -C petstore.cbl */

#include <stdio.h>
#include <string.h>
#define  COB_KEYWORD_INLINE __inline
#include <gmp.h>
#include <libcob.h>

#define  COB_SOURCE_FILE		"petstore.cbl"
#define  COB_PACKAGE_VERSION		"3.1-dev"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"May 13 2020 22:44:45"
#define  COB_MODULE_DATE		20200513
#define  COB_MODULE_TIME		224445

/* Global variables */
#include "petstore.c.h"

/* Function prototypes */

int		PETSTORE (void);
static int		PETSTORE_ (const int);
static void		PETSTORE_module_init (cob_module *module);

/* Functions */

/* PROGRAM-ID 'PETSTORE' */

/* ENTRY 'PETSTORE' */

int
PETSTORE ()
{
  return PETSTORE_ (0);
}

static int
PETSTORE_ (const int entry)
{
  /* Program local variables */
  #include "petstore.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -10)
  		goto P_dump;
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_ptr->return_address_ptr = &&P_cgerror;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Allocate decimal numbers */
  cob_decimal_alloc (2, &d0, &d1);

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 73        : Entry     PETSTORE                : petstore.cbl */
  l_2:;

  /* Line: 75        : Paragraph 0001-START              : petstore.cbl */

  /* Line: 76        : PERFORM            : petstore.cbl */
  /* PERFORM 0002-WELCOME-USER */
  frame_ptr++;
  frame_ptr->perform_through = 6;
  frame_ptr->return_address_ptr = &&l_14;
  goto l_6;
  l_14:
  frame_ptr--;

  /* Line: 77        : PERFORM            : petstore.cbl */
  for (;;)
  {
    if (((int)(int)(*(b_18 + 7) - 78) == 0))
      break;
    /* PERFORM 0003-ASK-FOR-ITEM */
    frame_ptr++;
    frame_ptr->perform_through = 8;
    frame_ptr->return_address_ptr = &&l_15;
    goto l_8;
    l_15:
    frame_ptr--;
  }

  /* Line: 78        : PERFORM            : petstore.cbl */
  /* PERFORM 0004-CALCULATE-DISCOUNT */
  frame_ptr++;
  frame_ptr->perform_through = 10;
  frame_ptr->return_address_ptr = &&l_16;
  goto l_10;
  l_16:
  frame_ptr--;

  /* Line: 79        : PERFORM            : petstore.cbl */
  /* PERFORM 0005-DISPLAY-BILL */
  frame_ptr++;
  frame_ptr->perform_through = 12;
  frame_ptr->return_address_ptr = &&l_17;
  goto l_12;
  l_17:
  frame_ptr--;

  /* Line: 80        : STOP RUN           : petstore.cbl */
  cob_stop_run (b_2);

  /* Line: 81        : Paragraph 0001-END                : petstore.cbl */

  /* Line: 83        : Paragraph 0002-WELCOME-USER       : petstore.cbl */
  l_6:;

  /* Line: 84        : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &c_1);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 6)
    goto *frame_ptr->return_address_ptr;

  /* Line: 85        : Paragraph 0002-END                : petstore.cbl */

  /* Line: 87        : Paragraph 0003-ASK-FOR-ITEM       : petstore.cbl */
  l_8:;

  /* Line: 88        : MOVE               : petstore.cbl */
  memcpy (b_8 + 29 * (b_9 - 1), "Item description", 16);

  /* Line: 89        : MOVE               : petstore.cbl */
  memcpy (b_8 + 16 + 29 * (b_9 - 1), "00999", 5);

  /* Line: 90        : MOVE               : petstore.cbl */
  memcpy (b_8 + 21 + 29 * (b_9 - 1), "009", 3);

  /* Line: 91        : COMPUTE            : petstore.cbl */
  cob_decimal_set_field (d0, COB_SET_FLD(f0, 3, b_8 + 21 + 29 * (b_9 - 1), &a_2));
  cob_decimal_set_field (d1, COB_SET_FLD(f0, 5, b_8 + 16 + 29 * (b_9 - 1), &a_3));
  cob_decimal_mul (d0, d1);
  cob_decimal_get_field (d0, COB_SET_FLD(f0, 5, b_8 + 24 + 29 * (b_9 - 1), &a_3), 0);

  /* Line: 92        : ADD                : petstore.cbl */
  cob_add_int (&f_15, cob_get_numdisp (b_8 + 21 + 29 * (b_9 - 1), 3), 0);

  /* Line: 93        : ADD                : petstore.cbl */
  cob_add (&f_16, COB_SET_FLD(f0, 5, b_8 + 24 + 29 * (b_9 - 1), &a_3), 0);

  /* Line: 94        : ADD                : petstore.cbl */
  b_9 = (b_9 + 1);

  /* Line: 95        : MOVE               : petstore.cbl */
  *(b_18 + 7) = 78;

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 8)
    goto *frame_ptr->return_address_ptr;

  /* Line: 96        : Paragraph 0003-END                : petstore.cbl */

  /* Line: 98        : Paragraph 0004-CALCULATE-DISCOUNT : petstore.cbl */
  l_10:;

  /* Line: 99        : IF                 : petstore.cbl */
  if (((int)cob_cmp_llint (&f_16, cob_get_llint (&f_21)) > 0))
  {

    /* Line: 100       : COMPUTE            : petstore.cbl */
    cob_decimal_set_field (d0, &f_16);
    cob_decimal_set_field (d1, &f_20);
    cob_decimal_mul (d0, d1);
    cob_decimal_get_field (d0, &f_17, 0);
  }
  else
  {
    /* ELSE */

    /* Line: 102       : MOVE               : petstore.cbl */
    memcpy (b_14 + 10, b_14 + 3, 7);
  }

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 10)
    goto *frame_ptr->return_address_ptr;

  /* Line: 104       : Paragraph 0004-END                : petstore.cbl */

  /* Line: 106       : Paragraph 0005-DISPLAY-BILL       : petstore.cbl */
  l_12:;

  /* Line: 107       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 108       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &c_2);

  /* Line: 109       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_24);

  /* Line: 110       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_32);

  /* Line: 111       : PERFORM            : petstore.cbl */
  memcpy (b_18, "001", 3);
  for (;;)
  {
    if (((int)(cob_get_numdisp (b_18, 3) - b_9) == 0))
      break;

    /* Line: 112       : MOVE               : petstore.cbl */
    memcpy (b_40, b_8 + 29 * (cob_get_int (&f_19) - 1), 16);

    /* Line: 113       : MOVE               : petstore.cbl */
    cob_move (COB_SET_FLD(f0, 5, b_8 + 16 + 29 * (cob_get_int (&f_19) - 1), &a_3), &f_43);

    /* Line: 114       : MOVE               : petstore.cbl */
    cob_move (COB_SET_FLD(f0, 3, b_8 + 21 + 29 * (cob_get_int (&f_19) - 1), &a_2), &f_45);

    /* Line: 115       : MOVE               : petstore.cbl */
    cob_move (COB_SET_FLD(f0, 5, b_8 + 24 + 29 * (cob_get_int (&f_19) - 1), &a_3), &f_47);

    /* Line: 116       : DISPLAY            : petstore.cbl */
    cob_display (0, 1, 1, &f_40);
    cob_add_int (&f_19, 1, 0);
  }

  /* Line: 118       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_48);

  /* Line: 119       : MOVE               : petstore.cbl */
  cob_move (&f_15, &f_55);

  /* Line: 120       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_51);

  /* Line: 121       : MOVE               : petstore.cbl */
  cob_move (&f_16, &f_60);

  /* Line: 122       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_56);

  /* Line: 123       : MOVE               : petstore.cbl */
  cob_move (&f_17, &f_65);

  /* Line: 124       : DISPLAY            : petstore.cbl */
  cob_display (0, 1, 1, &f_61);

  /* Implicit PERFORM return */
  if (frame_ptr->perform_through == 12)
    goto *frame_ptr->return_address_ptr;

  /* Line: 125       : Paragraph 0005-END                : petstore.cbl */

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;
  P_cgerror:
  	cob_fatal_error (COB_FERROR_CODEGEN);


  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  PETSTORE_module_init (module);

  module->crt_status = NULL;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  b_9 = 1;
  for (i0 = 1; i0 <= 100; i0++)
  {
    memset (b_8 + 29 * (i0 - 1), 32, 16);
    memset (b_8 + 16 + 29 * (i0 - 1), 48, 13);
  }
  memset (b_14, 48, 3);
  memset (b_14 + 3, 48, 7);
  memset (b_14 + 10, 48, 7);
  memcpy (b_18, "001", 3);
  *(b_18 + 3) = 56;
  memcpy (b_18 + 4, "100", 3);
  *(cob_u8_ptr)(b_18 + 7) = 32;
  memcpy (b_24, "PRODUCT", 7);
  memset (b_24 + 7, 32, 9);
  memset (b_24 + 16, 32, 2);
  memcpy (b_24 + 18, "PRICE", 5);
  memset (b_24 + 18 + 5, 32, 5);
  memset (b_24 + 28, 32, 2);
  memcpy (b_24 + 30, "QUANTITY", 8);
  memset (b_24 + 38, 32, 2);
  memcpy (b_24 + 40, "COST", 4);
  memset (b_24 + 40 + 4, 32, 6);
  memset (b_32, 61, 16);
  memset (b_32 + 16, 32, 2);
  memset (b_32 + 18, 61, 10);
  memset (b_32 + 28, 32, 2);
  memset (b_32 + 30, 61, 8);
  memset (b_32 + 38, 32, 2);
  memset (b_32 + 40, 61, 10);
  memset (b_40, 32, 16);
  memset (b_40 + 16, 32, 2);
  cob_move (&cob_all_zero, &f_43);
  memset (b_40 + 28, 32, 2);
  cob_move (&cob_all_zero, &f_45);
  memset (b_40 + 38, 32, 2);
  cob_move (&cob_all_zero, &f_47);
  memset (b_48, 32, 40);
  memset (b_48 + 40, 61, 10);
  memset (b_51, 32, 32);
  memcpy (b_51 + 32, "Items:", 6);
  memset (b_51 + 38, 32, 2);
  cob_move (&cob_all_zero, &f_55);
  memset (b_56, 32, 32);
  memcpy (b_56 + 32, "Total:", 6);
  memset (b_56 + 38, 32, 2);
  cob_move (&cob_all_zero, &f_60);
  memset (b_61, 32, 27);
  memcpy (b_61 + 27, "Discounted:", 11);
  memset (b_61 + 38, 32, 2);
  cob_move (&cob_all_zero, &f_65);

  if (0 == 1) goto P_cgerror;
  initialized = 1;
  goto P_ret_initialize;

  P_dump:
  return 0;


  /* CANCEL callback handling */
  P_cancel:

  if (!initialized)
  	return 0;
  if (module && module->module_active)
  	cob_fatal_error (COB_FERROR_CANCEL);

  b_2 = 0;
  cob_module_free (&module);

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'PETSTORE' */

/* Initialize module structure for PETSTORE */
static void PETSTORE_module_init (cob_module *module)
{
  module->module_name = "PETSTORE";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())PETSTORE;
  module->module_cancel.funcptr = (void *(*)())PETSTORE_;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 0;
  module->flag_main = 0;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;
  module->flag_debug_trace = 0;
  module->flag_dump_ready = 0;
  module->module_stmt = 0;
  module->module_sources = NULL;
}

/* End functions */

