/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
/* Generated at           Apr 23 2020 17:56:17 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -d -fdebugging-line -fsource-location -ftraceall /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl subsample.cbl subsubsample.cbl */

/* Program local variables for 'sample' */

/* Module initialization indicator */
static unsigned int	initialized = 0;

/* Module structure pointer */
static cob_module	*module = NULL;

/* Global variable pointer */
cob_global		*cob_glob_ptr;


/* Call pointers */
static cob_call_union	call_subsample;

/* Call parameters */
cob_field		*cob_procedure_params[1];

/* Perform frame stack */
struct cob_frame	*frame_overflow;
struct cob_frame	*frame_ptr;
struct cob_frame	frame_stack[255];


/* Data storage */
static int	b_2;	/* RETURN-CODE */
static cob_u8_t	b_6[2] __attribute__((aligned));	/* WS-NUMERIC */
static cob_u8_t	b_7[5] __attribute__((aligned));	/* WS-SIGNED-DECIMAL */
static cob_u8_t	b_8[5] __attribute__((aligned));	/* WS-UNSIGNED-DECIMAL */
static cob_u8_t	b_9[6] __attribute__((aligned));	/* WS-ALPHABETIC */
static cob_u8_t	b_10[5] __attribute__((aligned));	/* WS-ALPHANUMERIC */
static cob_u8_t	b_11[23] __attribute__((aligned));	/* WS-GROUP */
static cob_u8_t	b_17[2] __attribute__((aligned));	/* WS-CHECK */

/* End of data storage */


/* Fields */
static cob_field f_11	= {23, b_11, &a_2};	/* WS-GROUP */

/* End of fields */

