/* Generated by           cobc 2.2.0 */
/* Generated from         /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
/* Generated at           Apr 23 2020 17:56:17 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -d -fdebugging-line -fsource-location -ftraceall /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl subsample.cbl subsubsample.cbl */

#include <stdio.h>
#include <stdlib.h>
#include <stddef.h>
#include <string.h>
#include <math.h>
#define  COB_KEYWORD_INLINE __inline
#include <libcob.h>

#define  COB_SOURCE_FILE		"/home/olegs/projects/gnucobol-debug/test/resources/sample.cbl"
#define  COB_PACKAGE_VERSION		"2.2"
#define  COB_PATCH_LEVEL		0
#define  COB_MODULE_FORMATTED_DATE	"Apr 23 2020 17:56:17"
#define  COB_MODULE_DATE		20200423
#define  COB_MODULE_TIME		175617

/* Global variables */
#include "sample.c.h"

/* Function prototypes */

static int		sample ();
static int		sample_ (const int);

/* Main function */
int
main (int argc, char **argv)
{
  cob_init (argc, argv);
  cob_stop_run (sample ());
}

/* Functions */

/* PROGRAM-ID 'sample' */

/* ENTRY 'sample' */

static int
sample ()
{
  return sample_ (0);
}

static int
sample_ (const int entry)
{
  /* Program local variables */
  #include "sample.c.l.h"

  /* Start of function code */

  /* CANCEL callback */
  if (unlikely(entry < 0)) {
  	if (entry == -20)
  		goto P_clear_decimal;
  	goto P_cancel;
  }

  /* Check initialized, check module allocated, */
  /* set global pointer, */
  /* push module stack, save call parameter count */
  if (cob_module_global_enter (&module, &cob_glob_ptr, 0, entry, 0))
  	return -1;

  /* Set address of module parameter list */
  module->cob_procedure_params = cob_procedure_params;

  /* Set frame stack pointer */
  frame_ptr = frame_stack;
  frame_ptr->perform_through = 0;
  frame_overflow = frame_ptr + 255 - 1;

  /* Initialize rest of program */
  if (unlikely(initialized == 0)) {
  	goto P_initialize;
  }
  P_ret_initialize:

  /* Increment module active */
  module->module_active++;

  /* Entry dispatch */
  goto l_2;

  /* PROCEDURE DIVISION */

  /* Line: 20        : Entry     sample                  : /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
  l_2:;
  cob_trace_section (st_2, st_1, 20);
  cob_trace_section (st_3, st_1, 20);
  cob_trace_section (st_4, st_1, 20);

  /* Line: 20        : DISPLAY            : /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
  cob_set_location (st_1, 20, NULL, NULL, st_5);
  cob_display (0, 1, 1, &c_1);

  /* Line: 21        : CALL               : /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
  cob_set_location (st_1, 21, NULL, NULL, st_6);
  {
    union {
    	unsigned char data[23];
    	cob_s64_t     datall;
    	cob_u64_t     dataull;
    	int           dataint;
    } content_1;
    cob_field      content_f_1;
    cob_field_attr content_a_1;

    cob_field_constant (&f_11, &content_f_1 , &content_a_1 , &content_1);
    cob_procedure_params[0] = &content_f_1;
    cob_glob_ptr->cob_call_params = 1;
    cob_glob_ptr->cob_stmt_exception = 0;
    if (unlikely(call_subsample.funcvoid == NULL || cob_glob_ptr->cob_physical_cancel)) {
      call_subsample.funcvoid = cob_resolve_cobol ("subsample", 0, 1);
    }
    b_2 = ((int (*)(void *))call_subsample.funcint) (content_1.data);
  }

  /* Line: 23        : DISPLAY            : /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
  cob_set_location (st_1, 23, NULL, NULL, st_5);
  cob_display (0, 1, 1, &c_2);

  /* Line: 24        : STOP RUN           : /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl */
  cob_set_location (st_1, 24, NULL, NULL, st_7);
  cob_stop_run (b_2);

  /* Program exit */

  /* Decrement module active count */
  if (module->module_active) {
  	module->module_active--;
  }

  /* Trace program exit */
  cob_trace_section (st_8, NULL, 0);

  /* Pop module stack */
  cob_module_leave (module);

  /* Program return */
  return b_2;

  /* Program initialization */
  P_initialize:

  cob_check_version (COB_SOURCE_FILE, COB_PACKAGE_VERSION, COB_PATCH_LEVEL);

  cob_module_path = cob_glob_ptr->cob_main_argv0;

  /* Initialize module structure */
  module->module_name = "sample";
  module->module_formatted_date = COB_MODULE_FORMATTED_DATE;
  module->module_source = COB_SOURCE_FILE;
  module->module_entry.funcptr = (void *(*)())sample;
  module->module_cancel.funcptr = (void *(*)())sample_;
  module->collating_sequence = NULL;
  module->crt_status = NULL;
  module->cursor_pos = NULL;
  module->module_ref_count = NULL;
  module->module_path = &cob_module_path;
  module->module_active = 0;
  module->module_date = COB_MODULE_DATE;
  module->module_time = COB_MODULE_TIME;
  module->module_type = 0;
  module->module_param_cnt = 0;
  module->module_returning = 0;
  module->ebcdic_sign = 0;
  module->decimal_point = '.';
  module->currency_symbol = '$';
  module->numeric_separator = ',';
  module->flag_filename_mapping = 1;
  module->flag_binary_truncate = 1;
  module->flag_pretty_display = 1;
  module->flag_host_sign = 0;
  module->flag_no_phys_canc = 1;
  module->flag_main = 1;
  module->flag_fold_call = 0;
  module->flag_exit_program = 0;

  /* Initialize cancel callback */
  cob_set_cancel (module);

  /* Initialize WORKING-STORAGE */
  b_2 = 0;
  memcpy (b_6, "45", 2);
  memcpy (b_7, "1234u", 5);
  memcpy (b_8, "12345", 5);
  memcpy (b_9, "ABCDEF", 6);
  memcpy (b_10, "A121$", 5);
  memcpy (b_11, "45", 2);
  memcpy (b_11 + 2, "1234u", 5);
  memcpy (b_11 + 7, "12345", 5);
  memcpy (b_11 + 12, "ABCDEF", 6);
  memcpy (b_11 + 18, "A121$", 5);
  memset (b_17, 48, 2);

  initialized = 1;
  goto P_ret_initialize;

  /* CANCEL callback handling */
  P_cancel:

  if (!initialized) {
  	return 0;
  }
  if (module->module_active) {
  	cob_fatal_error (COB_FERROR_CANCEL);
  }

  initialized = 0;

  P_clear_decimal:

  return 0;

}

/* End PROGRAM-ID 'sample' */

/* End functions */

