/* Generated by           cobc 2.2.0 */
/* Generated from         subsample.cbl */
/* Generated at           Apr 23 2020 17:56:17 */
/* GnuCOBOL build date    Jul 17 2018 20:29:40 */
/* GnuCOBOL package date  Sep 06 2017 18:48:43 UTC */
/* Compile command        cobc -free -x -g -d -fdebugging-line -fsource-location -ftraceall /home/olegs/projects/gnucobol-debug/test/resources/sample.cbl subsample.cbl subsubsample.cbl */


/* Module path */
static const char		*cob_module_path = NULL;

/* Number of call parameters */
static int		cob_call_params = 0;

/* Attributes */

static const cob_field_attr a_1 =	{0x21,   0,   0, 0x0000, NULL};
static const cob_field_attr a_2 =	{0x01,   0,   0, 0x0000, NULL};


/* Strings */
static const char st_1[]	= "subsample.cbl";
static const char st_2[]	= "Entry:     subsample";
static const char st_3[]	= "Section:   (None)";
static const char st_4[]	= "Paragraph: (None)";
static const char st_5[]	= "DISPLAY";
static const char st_6[]	= "CALL";
static const char st_7[]	= "Exit:      subsample";

